[pytest]
python_functions = test_* bench*
python_files = test_*.py *_test.py bench_*.py
addopts = --ptjb-output-dir=benchmarks/.results --ptjb-plot -s 
; addopts = --ptjb-output-dir=benchmarks/.results --ptjb-plot -s --ptjb-pin 26383
testpaths = benchmarks tests
filterwarnings =
    error